{% set name = "stackvana-core-recipe" %}
# LSST DM versions are prefixed with letters
#
#  - a weekly build is 'w_2018_50'
#  - a major release is 'v18_1'
#
# In order to play nice with conda, we take the following conventions
#
#  - for a weekly build 'w_2018_50', the conda version is '2018.50w'
#  - for a major version 'v18_1', the conda version is '18.1.0'
#
# Note the exta micro version in order to match the tags in the DM eups system.
{% set version = "2019.44w" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  skip: True  # [win or py < 37]
  number: 2

outputs:
  - name: stackvana-core
    version: {{ version }}
    run_exports:
      - {{ pin_subpackage('stackvana-core-impl', exact=True) }}
    requirements:
      run:
        - {{ pin_subpackage('stackvana-core-impl', exact=True) }}

  - name: stackvana-core-impl
    version: {{ version }}
    script: build_impl.sh
    requirements:
      host:
        - python
        - pip
        - curl
        - git
        - make
        - cmake

        - {{ compiler('c') }}
        - {{ compiler('cxx') }}

        # these are needed to make the symlinks for remapping
        - doxygen =1.8.13
        - boost =1.69
        - boost-cpp =1.69
        - fftw =3.3.4
        - gsl =2.6
        - libapr =1.6.5
        - libaprutil =1.6.1
        - log4cxx =0.10.0
        - pybind11 =2.2.4
        - mpich =3.3
        - starlink-ast =8.7.2
        # - eigen =3.3.7
        - xpa =2.1.19
        - ndarray =1.5.3
        - lsstdesc.coord =1.2
        - treecorr =3.3.11
        - healpy =1.12.10
        - psutil
        - pep8-naming
        - ws4py
        - py
        - execnet
        - pytest >=4,<5.0.0a0
        - pytest-forked =0.2
        - pytest-xdist =1.20.1
        - coverage
        - pytest-cov
        - pyflakes
        - pycodestyle
        - mccabe
        - flake8
        - pytest-flake8
        - esutil >=0.6.4
        - requests
        - mpi4py
        - sqlalchemy
        - future
        - galsim >=2.2.1

        # and these are needed for the build of sconsUtils
        - setuptools_scm
        - apipkg >=1.4
        - pytest-runner
        - flake8-polyfill
        - numpy =1.16.2
      run:
        - python
        - pip
        - curl
        - git
        - make
        - cmake

        # "real" deps
        - astropy =3.2.3
        - blosc =1.15.0
        - h5py =2.9.0
        - hdf5 =1.10.4
        - matplotlib =3.0.3
        - numexpr =2.6.9
        - numpy =1.16.2
        - pandas =0.24.2
        - pyqt
        - qt
        - scikit-learn =0.20.3
        - scipy =1.2.1
        - snappy =1.1.7
        - deprecated =1.2.6

        # I am shipping these by hand from conda forge using remap
        - doxygen =1.8.13
        - boost =1.69
        - boost-cpp =1.69
        - fftw =3.3.4
        - gsl =2.6
        - libapr =1.6.5
        - libaprutil =1.6.1
        - log4cxx =0.10.0
        - pybind11 =2.2.4
        - mpich =3.3
        - starlink-ast =8.7.2
        # - eigen =3.3.7
        - xpa =2.1.19
        - ndarray =1.5.3
        - lsstdesc.coord =1.2
        - treecorr =3.3.11
        - healpy =1.12.10
        - psutil
        - pep8-naming
        - ws4py
        - py
        - execnet
        - pytest >=4,<5.0.0a0
        - pytest-forked =0.2
        - pytest-xdist =1.20.1
        - coverage
        - pytest-cov
        - pyflakes
        - pycodestyle
        - mccabe
        - flake8
        - pytest-flake8
        - esutil >=0.6.4
        - requests
        - mpi4py
        - sqlalchemy
        - future
        - galsim >=2.2.1

        # stuff added outside of the main LSST DM conda envs
        - flex
        - bison
        - setuptools_scm
        - apipkg >=1.4
        - pytest-runner
        - flake8-polyfill

        # compilers for compiling
        - c-compiler
        - cxx-compiler

    test:
      script: run_test_impl.sh

about:
  home: https://github.com/beckermr/stackvana-core
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: 'core build tooling for stackvana'

extra:
  recipe-maintainers:
    - beckermr
