{% set name = "stackvana-core-recipe" %}
# LSST DM versions are prefixed with letters
#
#  - a weekly build is 'w_2018_50'
#  - a major release is 'v18_1'
#
# In order to play nice with conda, we take the following conventions
#
#  - for a weekly build 'w_2018_50', the conda version is '2018.50w'
#  - for a major version 'v18_1', the conda version is '18.1.0'
#
# Note the exta micro version in order to match the tags in the DM eups system.
{% set version = "2020.24w" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  skip: true  # [win or py != 37]
  number: 1
  merge_build_host: True

outputs:
  - name: stackvana-core
    version: {{ version }}
    run_exports:
      - {{ pin_subpackage('stackvana-core-impl', exact=True) }}
    requirements:
      run:
        - {{ pin_subpackage('stackvana-core-impl', exact=True) }}

  - name: stackvana-core-impl
    version: {{ version }}
    script: build_impl.sh
    requirements:
      host:
        # build dependencies
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - doxygen
        - flake8 <3.8
        - git
        - git-lfs
        - make
        - pep8-naming
        - psutil
        - pytest
        - pytest-cov
        - pytest-doctestplus
        - pytest-flake8
        - pytest-runner
        - pytest-session2file ==0.1.9
        - pytest-subtests
        - pytest-xdist
        - scons
        - python =3.7

        # this is extra
        - curl
      run:
        # build dependencies
        - c-compiler
        - cxx-compiler
        - cmake
        - doxygen
        - flake8 <3.8
        - git
        - git-lfs
        - make
        - pep8-naming
        - psutil
        - pytest
        - pytest-cov
        - pytest-doctestplus
        - pytest-flake8
        - pytest-runner
        - pytest-session2file ==0.1.9
        - pytest-subtests
        - pytest-xdist
        - scons

        # host dependencies
        - apr
        - autograd
        - astropy
        - boost
        - boto3
        - bottleneck
        - cffi
        - cfitsio
        - click <7.1
        - cython
        - deprecated
        - eigen
        - esutil
        - fastavro
        - future
        - galsim
        - gsl
        - h5py
        - healpy
        - libaprutil
        - blas-devel
        - log4cxx
        - lmfit
        - lsstdesc.coord
        - matplotlib =3.0
        - minuit2
        - moto
        - mpich
        - mpi4py
        - ndarray
        - numexpr
        - numpy
        - pandas
        - pip
        - pyarrow
        - pybind11 <2.3
        - pyqt <5.12 # For matplotlib on linux. See https://github.com/conda-forge/pyqt-feedstock/issues/77
        - pytables
        - python =3.7
        - pyyaml
        - requests
        - scikit-image
        - scikit-learn
        - scipy
        - starlink-ast
        - sqlalchemy
        - treecorr <4
        - wcslib
        - ws4py
        - xpa

        # this is extra
        - curl
    test:
      script: run_test_impl.sh

about:
  home: https://github.com/beckermr/stackvana-core
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: 'core build tooling for stackvana'

extra:
  recipe-maintainers:
    - beckermr
