{% set name = "stackvana-core-recipe" %}
# LSST DM versions are prefixed with letters
#
#  - a weekly build is 'w_2018_50'
#  - a major release is 'v18_1'
#
# In order to play nice with conda, we take the following conventions
#
#  - for a weekly build 'w_2018_50', the conda version is '2018.50w'
#  - for a major version 'v18_1', the conda version is '18.1.0'
#
# Note the exta micro version in order to match the tags in the DM eups system.
{% set version = "2020.40w" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  skip: true  # [win or py != 37]
  number: 0
  merge_build_host: True

requirements:
  host:
    - python
  run:
    - python

outputs:
  - name: stackvana-core
    version: {{ version }}
    run_exports:
      - {{ pin_subpackage('stackvana-core-impl', exact=True) }}
    requirements:
      run:
        - {{ pin_subpackage('stackvana-core-impl', exact=True) }}

  - name: stackvana-core-impl
    version: {{ version }}
    script: build_impl.sh
    requirements:
      host:
        - python
        - pip
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}

        # build dependencies
        - cmake
        - doxygen
        - flake8 <3.8
        - git
        - git-lfs
        - make
        - patch
        - pep8-naming
        - psutil
        - pytest <6
        - pytest-cov
        - pytest-doctestplus !=0.7.0
        - pytest-flake8
        - pytest-runner
        - pytest-session2file !=0.1.10
        - pytest-subtests
        - pytest-xdist
        - scons

        - curl
      run:
        - python
        - pip

        # build dependencies
        - cmake
        - doxygen
        - flake8 <3.8
        - git
        - git-lfs
        - make
        - patch
        - pep8-naming
        - psutil
        - pytest <6
        - pytest-cov
        - pytest-doctestplus !=0.7.0
        - pytest-flake8
        - pytest-runner
        - pytest-session2file !=0.1.10
        - pytest-subtests
        - pytest-xdist
        - scons

        # host dependencies
        - apr
        - autograd
        - astropy =4
        - boost-cpp =1.70
        - boto3
        - bottleneck
        - cffi
        - click <7.1
        - cython
        - deprecated
        - eigen
        - esutil
        - fastavro <0.24
        - future
        - galsim
        - h5py
        - healpy
        - libaprutil
        - log4cxx
        - lmfit
        - lsstdesc.coord
        - matplotlib
        - minuit2
        - moto
        - mpi4py
        - ndarray <1.6
        - numexpr
        - pandas
        - pyarrow
        - pybind11 <2.3
        - pyqt <5.12 # For matplotlib on linux. See https://github.com/conda-forge/pyqt-feedstock/issues/77
        - pytables
        - pyyaml
        - requests
        - scikit-image
        - scikit-learn
        - scipy
        - starlink-ast <9
        - sqlalchemy
        - treecorr <4
        - wcslib
        - ws4py
        - xpa
    test:
      script: run_test_impl.sh
      requires:
        - python
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cfitsio
        - curl
        - fftw
        - gsl
        - hdf5
        - hdf5 * mpi_mpich_*
        - libblas
        - libcblas
        - liblapack
        - liblapacke
        - mpich
        - numpy >=1.17

  - name: stackvana-afw
    version: {{ version }}
    script: build_afw.sh
    requirements:
      host:
        - python
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ pin_subpackage('stackvana-core', exact=True) }}
        - cfitsio
        - curl
        - fftw
        - gsl
        - hdf5
        - hdf5 * mpi_mpich_*
        - libblas
        - libcblas
        - liblapack
        - liblapacke
        - mpich
        - numpy 1.17.*
      run:
        - python
        - {{ pin_subpackage('stackvana-core', exact=True) }}
        - cfitsio
        - curl
        - fftw
        - gsl
        - hdf5
        - hdf5 * mpi_mpich_*
        - mpich
        - {{ pin_compatible('numpy') }}
    test:
      script: run_test_afw.sh


about:
  home: https://github.com/beckermr/stackvana-core
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: 'core build tooling for stackvana'

extra:
  recipe-maintainers:
    - beckermr
