{% set name = "stackvana-core" %}
# LSST DM versions are prefixed with letters
#
#  - a weekly build is 'w_2018_50'
#  - a major release is 'v18_1'
#
# In order to play nice with conda, we take the following conventions
#
#  - for a weekly build 'w_2018_50', the conda version is '2018.50w'
#  - for a major version 'v18_1', the conda version is '18.1.0'
#
# Note the exta micro version in order to match the tags in the DM eups system.
{% set version = "18.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0
  skip: True  # [win or py < 37]
  run_exports:
    strong:
      - {{ pin_subpackage('stackvana-core', max_pin='x.x.x') }}

requirements:
  host:
    - python
    - pip
    - curl
    - git
    - perl
    - make
    - cmake
    - doxygen =1.8.13
  run:
    - python
    - pip
    - curl
    - git
    - perl
    - make
    - cmake

    # "real" deps
    - expat =2.2.5
    - more-itertools =6.0.0
    - attrs =17.4.0
    - atomicwrites =1.3.0
    - six =1.12.0
    - pluggy =0.6
    - astropy =3.1.2
    - numpy =1.16.2
    - scipy =1.2.1
    - h5py =2.9.0
    - hdf5 =1.10.4
    - blosc =1.15.0
    - matplotlib =3.0.3
    - pandas =0.24.2
    - scikit-learn =0.20.3
    - snappy =1.1.7
    - numexpr =2.6.9
    - future =0.17.1
    - deprecated =1.2.6
    - xorg-libxt =1.2.0  # [linux]
    - zlib =1.2.11
    - libiconv =1.15
    - doxygen =1.8.13
    - flex
    - bison

    # compilers for compiling
    - c-compiler
    - cxx-compiler
    - fortran-compiler

test:
  imports:
    - eups

about:
  home: https://github.com/beckermr/stackvana-core
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: 'core build tooling for stackvana'

extra:
  recipe-maintainers:
    - beckermr
