{% set name = "stackvana-core-recipe" %}
# LSST DM versions are prefixed with letters
#
#  - a weekly build is 'w_2018_50'
#  - a major release is 'v18_1'
#
# In order to play nice with conda, we take the following conventions
#
#  - for a weekly build 'w_2018_50', the conda version is '2018.50w'
#  - for a major version 'v18_1', the conda version is '18.1.0'
#
# Note the exta micro version in order to match the tags in the DM eups system.
{% set version = "2019.40w" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  skip: True  # [win or py < 37]
  number: 0

outputs:
  - name: stackvana-core
    version: {{ version }}
    run_exports:
      - {{ pin_subpackage('stackvana-core-impl', exact=True) }}
    requirements:
      run:
        - {{ pin_subpackage('stackvana-core-impl', exact=True) }}
    test:
      script: run_test_impl.sh

  - name: stackvana-core-impl
    version: {{ version }}
    script: build_impl.sh
    requirements:
      host:
        - python
        - pip
        - curl
        - git
        - make
        - cmake

        - {{ compiler('c') }}
        - {{ compiler('cxx') }}

        # these are needed to make the symlinks for remapping
        - doxygen =1.8.13
        - boost =1.69  # [linux]
        - boost-cpp =1.69  # [linux]
        - fftw =3.3.4  # [linux]
        - gsl =2.6  # [linux]
        - libapr =1.6.5  # [linux]
        - libaprutil =1.6.1  # [linux]
        - log4cxx =0.10.0  # [linux]
        - pybind11 =2.2.4  # [linux]
        - mpich =3.3  # [linux]

        # and these are needed for the build of sconsUtils
        - setuptools_scm
        - apipkg >=1.4
        - pytest-runner
        - pytest-flake8
        - flake8-polyfill
        - pluggy =0.6
        - expat =2.2.5
        - more-itertools =6.0.0
        - attrs =17.4.0
        - atomicwrites =1.3.0
        - six =1.12.0
        - numpy =1.16.2
        - expat =2.2.5
        - zlib =1.2.11
        - libiconv =1.15
      run:
        - python
        - pip
        - curl
        - git
        - make
        - cmake

        # "real" deps
        - expat =2.2.5
        - more-itertools =6.0.0
        - attrs =17.4.0
        - atomicwrites =1.3.0
        - six =1.12.0
        - pluggy =0.6
        - astropy =3.1.2
        - numpy =1.16.2
        - scipy =1.2.1
        - h5py =2.9.0
        - hdf5 =1.10.4
        - blosc =1.15.0
        - matplotlib =3.0.3
        - pandas =0.24.2
        - scikit-learn =0.20.3
        - snappy =1.1.7
        - numexpr =2.6.9
        - future =0.17.1
        - deprecated =1.2.6
        - zlib =1.2.11
        - libiconv =1.15

        # I am shipping these by hand from conda forge using remap
        - doxygen =1.8.13
        - boost =1.69  # [linux]
        - boost-cpp =1.69  # [linux]
        - fftw =3.3.4  # [linux]
        - gsl =2.6  # [linux]
        - libapr =1.6.5  # [linux]
        - libaprutil =1.6.1  # [linux]
        - log4cxx =0.10.0  # [linux]
        - pybind11 =2.2.4  # [linux]
        - mpich =3.3  # [linux]

        # stuff added outside of the main LSST DM conda envs
        - xorg-libxt =1.2.0  # [linux]
        - flex
        - bison
        - setuptools_scm
        - apipkg >=1.4
        - pytest-runner
        - pytest-flake8
        - flake8-polyfill

        # these deps shadow those installed by eups
        # this means two copies are in the final downstream envs
        # this tends to help the build
        - pytest =3.6.2
        - lsstdesc.coord =1.1

        # compilers for compiling
        - c-compiler
        - cxx-compiler

    test:
      script: run_test_impl.sh

about:
  home: https://github.com/beckermr/stackvana-core
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: 'core build tooling for stackvana'

extra:
  recipe-maintainers:
    - beckermr
